spring:
  cloud:
    config:
      uri: 'http://configservice:8888'
      fail-fast: true
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
     defaultZone: http://serviceregistry:8761/eureka
  instance:
    preferIpAddress: true
management:
  security:
    enabled: false
logging:
    level: DEBUG
    com.netflix.discovery: DEBUG
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
ribbon:
    ConnectTimeout: 60000
    ReadTimeout: 60000
